import { AreaType } from "./area.types";
import { CompanyType } from "./company.types";
import { CityType } from "./city.types";
import { BillboardTypeType } from "./billboard-type.types";
import { ClientType } from "./client.types";

export type BillboardType = {
    id: string;
    reference: string;
    pathBrochure: string;
    pathContract: string;
    pathFile: string;
    pathPhoto: string;
    typeId: string;
    type: BillboardTypeType;
    name: string;
    locationDuration: Date[];
    dimension: string;
    city: CityType
    placement: AreaType;
    cityId: string;
    placementId: string;
    revenueGenerate: String;
    orientation: string;
    information?: string;
    address: string;
    gmaps: string;
    zone: string;
    visibility: string;
    rentalPrice: string;
    installationCost: string;
    maintenance: string;
    imageFiles: string[];
    brochureFiles: string[];
    structure: string;
    decorativeElement: string;
    foundations: string;
    technicalVisibility: string;
    note: string;
    lessorType: string;
    lessorName: string;
    lessorEmail: string;
    lessorPhone: string;
    lessorJob: string;
    capital: string;
    rccm: string;
    taxIdentificationNumber: string;
    lessorAddress: string;
    representativeName: string;
    representativeContract: string;
    leasedSpace: string;
    contractDuration: Date[];
    paymentMethod: string;
    specificCondition: string;
    signedLeaseContract: string[];
    files: string[];
    companyId: string;
    company: CompanyType<string>;
    clientId: string;
    client: ClientType;
    createdAt: Date;
    updatedAt: Date;
};
