import {
  AppointmentIcon,
  BillboardIcon,
  ClientIcon,
  CreditNoteIcon,
  DashboardIcon,
  DeliveryNoteIcon,
  InvoiceIcon,
  ProductServiceIcon,
  ProjetIcon,
  PurchaseOrderIcon,
  QuoteIcon,
  SettingIcon,
  SupplierIcon,
  TransactionIcon,
} from "@/components/icons";
import { WebsiteType } from "@/types/website.types";
import { ReceiptTextIcon } from "lucide-react";

export const website: WebsiteType = {
  sidebarMenu: [
    {
      id: 1,
      icon: <DashboardIcon />,
      title: "Dashboard",
      path: "/overview",
      resource: "DASHBOARD",
    },
    {
      id: 2,
      icon: <ClientIcon />,
      title: "Clients",
      path: "/client",
      resource: "CLIENTS",
    },
    {
      id: 3,
      icon: <SupplierIcon />,
      title: "Fournisseurs",
      path: "/supplier",
      resource: "SUPPLIERS",
    },
    {
      id: 4,
      icon: <InvoiceIcon />,
      title: "Factures",
      path: "/invoice",
      resource: "INVOICES",
    },
    {
      id: 5,
      icon: <QuoteIcon />,
      title: "Devis",
      path: "/quote",
      resource: "QUOTES",
    },
    {
      id: 6,
      icon: <DeliveryNoteIcon />,
      title: "Bons de livraison",
      path: "/delivery-note",
      resource: "DELIVERY_NOTES",
    },
    {
      id: 7,
      icon: <PurchaseOrderIcon />,
      title: "Bons de commande",
      path: "/purchase-order",
      resource: "PURCHASE_ORDER",
    },
    {
      id: 8,
      icon: <CreditNoteIcon />,
      title: "Avoirs",
      path: "/credit",
      resource: "CREDIT_NOTES",
    },
    {
      id: 9,
      icon: <ProductServiceIcon />,
      title: "Produits et Services",
      path: "/product",
      resource: "PRODUCT_SERVICES",
    },
    {
      id: 10,
      icon: <BillboardIcon />,
      title: "Panneaux d'affichage",
      path: "/billboard",
      resource: "BILLBOARDS",
    },
    {
      id: 11,
      icon: <ProjetIcon />,
      title: "Projets",
      path: "/project",
      resource: "PROJECTS",
    },
    {
      id: 12,
      icon: <AppointmentIcon />,
      title: "Rendez-vous",
      path: "/appointment",
      resource: "APPOINTMENT",
    },
    {
      id: 13,
      icon: <ReceiptTextIcon />,
      title: "Contrat",
      path: "/contract",
      resource: "CONTRACT",
    },
    {
      id: 14,
      icon: <TransactionIcon />,
      title: "Transaction",
      path: "/transaction",
      resource: "TRANSACTION",
    },
    {
      id: 15,
      icon: <SettingIcon />,
      title: "Paramètres",
      path: "/settings",
      resource: "SETTING",
    },
  ],
  adminOnlyPaths: ["/overview/profile/:id/edit"],
};
